/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, NativeModules} from 'react-native';
import RNPulsator from 'react-native-pulsator';

export default class App extends Component {
  render() {
    return (
      <View style={{marginTop: 120, marginLeft: 100, width: 100, height: 100}}>
        <RNPulsator
          style={{ backgroundColor: 'red', width: 200, height: 200 }}
          color="#ffffff"
          numPulse={15}
          radius={240.3}
          offset={{x: 50, y: 10}}>
          <View>
            <Text>Text</Text>
          </View>
        </RNPulsator>
      </View>
    );
  }
}
